version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: hexo-renderer-marked
    versions:
    - 4.0.0
  - dependency-name: hexo-theme-minidyne
    versions:
    - 3.2.2
