# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Minidyne demo
author: John Doe
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://hexo-theme-minidyne-demo.netlify.com

permalink_defaults:
  
# Home page setting
index_generator:
  path: ''
  order_by: -date

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: minidyne
theme_config:
  # default icon for a post
  default_post_icon: 🥑
  menu:
    Home: /
    About: /about
    Project: /project

  social_platforms:
    - url: https://stackoverflow.com/users/12345/johndoe
      icon: stackoverflow
      name: Stack Overflow
    - url: https://github.com/johndoe/
      icon: github
      type: github
      name: GitHub
      repository: johndoe.blog
    - url: https://linkedin.com/in/johndoe
      icon: linkedin
      type: linkedin
      name: LinkedIn
    - url: https://twitter.com/johndoe
      icon: twitter
      type: twitter
      name: Twitter
      account: johndoe
    - url: https://www.flickr.com/photos/johndoe/
      icon: flickr
      type: flickr
      name: Flickr
    - url: https://mastodon.social/@johndoe
      icon: mastodon
      type: mastodon
      name: Mastodon
    - url: /rss2.xml
      icon: rss
      type: rss
      name: Rss
